-- CREATE TABLE IF NOT EXISTS DEPART(
-- EMPLOYEE_ID TEXT,
-- NAME TEXT,
-- DEPARTMENT_ID TEXT,
-- MANAGER_ID TEXT,
-- SALARY REAL


-- );
-- INSERT INTO DEPART (EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY) VALUES
-- ('E001', 'John Doe', 'D001', 'M001', 60000),
-- ('E002', 'Jane Smith', 'D002', 'M002', 75000),
-- ('E003', 'Emily Davis', 'D001', 'M001', 62000),
-- ('E004', 'Michael Brown', 'D003', 'M003', 80000),
-- ('E005', 'Jessica Wilson', 'D002', 'M002', 72000);

SELECT * FROM DEPART;
SELECT DEPARTMENT_ID AS "department code",
SUM(SALARY) AS "total salary"
FROM DEPART
WHERE MANAGER_ID = 'M002'
GROUP BY DEPARTMENT_ID;
SELECT DEPARTMENT_ID, COUNT(*) AS "employee count"
FROM DEPART
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 2
SELECT* FROM DEPART WHERE NAME LIKE "%D";
SELECT* FROM DEPART ORDER BY SALARY DESC;

