#file=open("abc.txt")
#content=file.read()
#print(content)  
#file.close()
#file=open("abc.txt","w")
#file.write(" hello world")               
#file=open("abc.txt","a")
#file.write(" i love anime") 
file=open("abc.txt","r")