CREATE TABLE IF NOT EXISTS STUDENT(
ROLL_NO TEXT PRIMARY KEY,
NAME TEXT NOT NULL,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER



);
INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('R001', 'Alice Johnson', '123 Maple St', '555-1234', 20),
('R002', 'Bob Smith', '456 Oak St', '555-5678', 22),
('R003', 'Charlie Brown', '789 Pine St', '555-8765', 19);
SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE=20 AND ADDRESS='123 Maple St';
SELECT * FROM STUDENT WHERE AGE=19 AND NAME='Charlie Brown';
SELECT * FROM STUDENT WHERE AGE=22 OR NAME='Alice Johnson';
SELECT * FROM STUDENT WHERE AGE>22;
SELECT * FROM STUDENT WHERE ROLL='R002';