-- CREATE TABLE IF NOT EXISTS PROD(
-- PRODUCT_ID TEXT,
-- PRODUCT_NAME TEXT,
-- SUPPPLIER_ID TEXT,
-- CATEGORY_ID TEXT,
-- UNIT TEXT,
-- PRICE REAL

-- );
-- INSERT INTO PROD (PRODUCT_ID, PRODUCT_NAME, SUPPPLIER_ID, CATEGORY_ID, UNIT, PRICE)VALUES 
-- ('1', 'Chai', '1', '1', '10 boxes x 20 bags', 18.00),
-- ('2','Jam','1','2','12 - 550 ml jars', 10.00),
-- ('3','Aniseed Syrup','1','2','12 - 550 ml bottles', 10.00),
-- ('4','Chef Anton''s Cajun Seasoning','2','2','48 - 6 oz jars', 22.00),
-- ('5','Chef Anton''s Gumbo Mix','2','2','36 boxes', 21.35);

SELECT * FROM PROD;
SELECT AVG(PRICE) AS Average_Price FROM PRODUCTS;
SELECT SUM(PRICE) AS Total_Price FROM PRODUCTS;
SELECT MIN(PRICE) FROM PRODUCTS;
SELECT MAX(PRICE) FROM PRODUCTS;    
SELECT DISTINCT SUPPPLIER_ID FROM PRODUCTS; 
SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'C%';